 class MyAdvertismentState {}

class SubscribtionStateInitial extends MyAdvertismentState {}
class LoadingMyAdvanceDateSelectedState extends MyAdvertismentState {}
class AdvanceDateSelectedState extends MyAdvertismentState {}
class AllFilesCleared extends MyAdvertismentState {}
class FileNotPicked extends MyAdvertismentState {}
class FilePickedSuccessfully extends MyAdvertismentState {}
class FileAlreadyExists extends MyAdvertismentState {}
class FileRemovedSuccessfully extends MyAdvertismentState {}
class SuccessAddAdsToLawyerPackageState extends MyAdvertismentState {}
class ErrorAddAdsToLawyerPackageState extends MyAdvertismentState {}
class LoadingAddAdsToLawyerPackageState extends MyAdvertismentState {}
 class SuccessPackageDetailsState extends MyAdvertismentState {}
 class ErrorPackageDetailsState extends MyAdvertismentState {}
 class LoadingPackageDetailsState extends MyAdvertismentState {}
 class LoadingLawyerAdPackagesState extends MyAdvertismentState {}
 class ErrorLawyerPackageAdsState extends MyAdvertismentState {}
 class SuccessLawyerPackageAdsState extends MyAdvertismentState {}
 class LoadingLawyerPackageAdsState extends MyAdvertismentState {}
 class FilePickCancelled extends MyAdvertismentState {}
 class UpdateProfileError extends MyAdvertismentState {}
 class LoadingUserPackageState extends MyAdvertismentState {}
 class ErrorUserPackageState extends MyAdvertismentState {}
 class SuccessUserPackageState extends MyAdvertismentState {}
 class SuccessAddAdsState extends MyAdvertismentState {}
 class ErrorAddAdsState extends MyAdvertismentState {}
 class LoadingAddAdsState extends MyAdvertismentState {}
 class SuccessEventsDataState extends MyAdvertismentState {}
 class ErrorEventsDataState extends MyAdvertismentState {}
 class LoadingEventsDataState extends MyAdvertismentState {}
 class SuccessAnnouncementDataState extends MyAdvertismentState {}
 class ErrorAnnouncementDataState extends MyAdvertismentState {}
 class LoadingAnnouncementDataState extends MyAdvertismentState {}
 class SuccessGigsDataState extends MyAdvertismentState {}
 class ErrorGigsDataState extends MyAdvertismentState {}
 class LoadingGigsDataState extends MyAdvertismentState {}